### ISSUE TITLE
Handle "qed" step specially

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#10]
After playing with metamath-lamp, I think there are some simple ways that the UI could be easier to use by making "qed" special. All proofs have some final goal, here called "qed":

* If a statement is saved and there are no other statements, automatically label it as qed.
* Before and after doing any unification (and maybe other actions like adding a step), if there's a qed step, automatically move it the last step in the list.

The idea is to move "qed" to the end automatically, otherwise it can end up in weird places.

**Comment by david-a-wheeler** [comment]
That makes sense. I guess my real goal is "put the final goal in some place where it stays put". Having qed listed first seems a little odd to me, but I can imagine getting used to it. I'll be curious to try it out; sometimes the only way to see if something works is to try it.

**Comment by expln** [comment]
This is implemented on dev. I am documenting here what's been done.

* A new step type was added for steps - G (goal). Only one statement in the editor may have type G. If a user adds one more G step then an error will be shown. This is an artificial restriction. Technically mm-lamp can work with more than one G step, but this restriction may simplify implementation of some future features (for example, automatic renaming of hypotheses).
* New settings related to G type:
1. "Mark initial step as a goal" - this will mark the very first step added to the editor as G.
2. "Stick the goal step to the bottom" - this will ensure the G step is always located at the bottom in the editor.
* New setting "Initial step label" - This text is used as a label for the first step added to the editor. If empty - a label will be generated automatically.
