### ISSUE TITLE
Goal duplication puts step at end and also has type goal

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#107]
I selected the goal statement and clicked on "duplicate".

I expected it to create a new statement of type "P" (since there should be only 1 goal) and for the new statement to be just *above* the goal (since the goal should always be at the end if that setting is enabled, which it is).

In *practice* it added a second goal statement *after* the goal statement.

**Comment by expln** [comment]
Thanks for reporting this. I will include a fix to v11.

**Comment by david-a-wheeler** [comment]
No problem! It may be as simple as turning off the "goal" flag on a duplicate.

**Comment by expln** [comment]
You are right. The fix was that simple. It has been deployed to dev.
I am closing this issue because it is relevant only for dev, and it is fixed on dev and works exactly as described.
Please fill free to reopen this issue if not everything is fixed.
