### ISSUE TITLE
In visualizations, don't repeat if conclusion is all constants (low priority)

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#115]
In visualizations, if the concluding justification is *all* constants, then the resulting statement shouldn't be repeated because it adds no new information. E.g., if you visualize `df-2`, you see:

~~~~
---------------------
|- 2 = ( 1 + 1 )
|- 2 = ( 1 + 1 )
~~~~

There's no point in showing it twice, because there are no variables to map to. Being *able* to show the visualization is great even in this case, because it reveals that this conclusion really *is* all constants... we just don't need that duplicated.

**Comment by expln** [comment]
@david-a-wheeler  This is fixed on dev.

**Comment by expln** [comment]
This is available in version 15 https://expln.github.io/lamp/v15/index.html
