### ISSUE TITLE
Make TEMP mode (temporary mode) more obvious

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#117]
There's no visual indication of anything unusual when in TEMP mode. For a while didn't even know it existed, never mind when I was in it.

Currently the word "TEMP" is added to the header, but that's not usually visible on a smartphone, and on my computer I use lots of tabs so only the "T" is visible.

I suggest adding a visual indication.

I think the *easy* way would be to change the background of the editor command icon bar, e.g., to something reddish. Practically every one of them exists to make a change to the contents, so if it were a distinctly different color that indicated a warning (red or orange or something like that), that would be a clear indication that something different was going on. It could still be light enough that it would contrast with blue (so the icons could still be understood).

**Comment by expln** [comment]
I changed background color of the editor tab to orange in TEMP mode. It doesn't have big impact on how UI looks like, but it is still noticeable.

**Comment by david-a-wheeler** [comment]
Great!

I had in mind changing the color of the "editor command icon bar" (where add, duplicated, etc.) live, instead of the "editor tab" name, but this is 100% fine. It's visually obvious that *something* is different, and that's all I wanted.

Feel free to close this issue.

**Comment by expln** [comment]
The solution with changing the color of the "editor command icon bar" is indeed very easy. But I didn't want to have a long horizontal line in different color. Thanks for confirming the implemented solution is also fine. I am closing the issue.
