### ISSUE TITLE
Announce the release of v11?

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#120]
Did you plan to announce the release of metamath-lamp version 11 to the Metamath mailing list?

I think it's a very worthy thing to announce. You could look here to remind yourself of your accomplishments: https://github.com/expln/metamath-lamp/milestone/1

Something like this:

===

Metamath-lamp proof assistant version 11 has now been released. You can try it out here: https://expln.github.io/lamp/latest/index.html

Major additions:

* Added an "explorer tab" and dynamic tabs for existing proofs, enabling users to examine the current context at any time.
* Works well on smartphones (e.g., supports "long-click" or "long-tap")
* More unified UI - all edits by default use a "long-click".
* Supports identifying one provable statement as the "goal statement" and treats it specially, making the UI easier to use.
* Visualization can be enabled or disabled per justification
* More control over which fields are displayed during editing

Documentation is available at: https://lamp-guide.metamath.org/

**Comment by david-a-wheeler** [comment]
If you'd prefer that I announce it, please just say the word.

**Comment by expln** [comment]
Thank you David! I will announce it soon. I planned to do it later because I had to compose a text, but you've already done this, so I will announce today :)

**Comment by expln** [comment]
@david-a-wheeler  

David could you please announce  the release  as you proposed? Looks like I don't have time to do it today :)

**Comment by david-a-wheeler** [comment]
Sure!

**Comment by expln** [comment]
Thank you!
