### ISSUE TITLE
Add delete (trash can) when editing Description, Variables, and Disjoints (low priority)

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#123]
You can save, cancel, or question when editing Description, Variables, and Disjoints. However, sometimes you'd like to just delete the whole thing - it'd be nice to add a trash can icon as well.

**Comment by expln** [comment]
@david-a-wheeler This is ready on dev.

**Comment by expln** [comment]
This is available in version 15 https://expln.github.io/lamp/v15/index.html
