### ISSUE TITLE
Question on unused functions

### ISSUE THREAD

**Issue by billh0420** [expln/metamath-lamp#135]
I am reading over the code and trying to understand it.

If I come across an unused function, do you want an issue submitted about it?

I realize that the unused function might be for future use; or, it might be something left over when it was formerly being used and is no longer needed. In the latter case, it probably should be deleted.

Here is the example that I came across. In ReactDOMRe.res file, the function "external createElement:" seems to be unused. A global search didn't find it and if I comment it out then there is no compile error.

I may not understand why it is there. Or, it may be being used in a dynamic way. If you can shed some light on this, it may help me in my reading over your code.

**Comment by expln** [comment]
ReactDOMRe.res is not a project file, it is a part of the library node_modules/@rescript/react/src/legacy/ReactDOMRe.res. 

If you are interested in how this function may be used, you may read about it in the ReScript documentation https://rescript-lang.org/docs/react/latest/elements-and-jsx#creating-elements-from-component-functions  This page describes not exactly that function, but it is very close - it allows to create a react element by passing the name of a component, props and children. This function is in "legacy" directory, so probably it is deprecated.

> If I come across an unused function, do you want an issue submitted about it?

That's a good idea to remove unused forgotten code. I think no need to create a new issue for each such case. Please post your findings in this issue.

**Comment by expln** [comment]
I am closing this issue. If you find any unused functions please feel free to re-open this issue and post your findings here.
