### ISSUE TITLE
Allow merging multiple statements with one merge button click

### ISSUE THREAD

**Issue by CatsAreFluffy** [expln/metamath-lamp#149]
It'd make merging lots of stuff a lot faster.

**Comment by expln** [comment]
What do you mean by merging? There is a button which merges two identical statements. It merges in the sense that it removes one statement and replaces all references to it with references to the remaining statement. But what kind of merging do you mean? Can you provide an example/examples?

**Comment by CatsAreFluffy** [comment]
Yes, I mean that kind of merging. For example, when I'm applying a theorem that uses lots of abbreviations (like many group theory theorems), after unifying the arguments I have to click many times to merge the abbreviations.

**Comment by expln** [comment]
Ok, got it. I've just recently implemented this feature. I will deploy it to dev tomorrow and describe how it works.

**Comment by expln** [comment]
This is ready on dev https://expln.github.io/lamp/dev/index.html

Now you don't have to select statements to merge. If there are duplicated statements, you may just click the Merge button once and it will go over all the duplicated statements and will ask you what statement to use (and what to remove). For example, if there are two pairs of duplicated statements, then you may click the Merge button only once when all the statements are unselected, and the merge dialog will appear twice - one time for each of the pair.

Also, please check the "Merge similar steps automatically" setting here https://github.com/expln/metamath-lamp/issues/47#issuecomment-1666015080  Enabling this setting will merge duplicated statements automatically in some cases so you don't even need to click the Merge button.

**Comment by expln** [comment]
This is available in [version 16](https://expln.github.io/lamp/v16/index.html)
