### ISSUE TITLE
In Settings make it clear that "Alt" is sometimes labelled "Opt"

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#15]
A default MacOS keyboard doesn't have an "Alt" key, it has an "Opt" key that does the same thing.
I think it'd be clearer to new users if the "Settings" display made it clear, near the
"Edit statements by" entry, something like the following:

> On some keyboards 'Alt' is labelled as 'Opt'

I don't think you need to change the menu entries everywhere, as long as the user
gets appropriate hints that the same key has multiple names.
I'm not sure that *all* MacOS keyboards don't have an "Alt" key, which is why I'm suggesting
this specific wording to cover all bases.

**Comment by david-a-wheeler** [comment]
As I noted elsewhere, I don't think auto-detection will work. "On newer Mac keyboard models, the Option key sometimes bears the label “option”. On older models, you will find the term “alt” on the key."
https://www.ionos.com/digitalguide/websites/web-development/option-key-on-macs/
Also, many Mac users use external keyboards with varying labels. If you mention both names, you're covering all cases.

**Comment by expln** [comment]
This is implemented on dev. `On some keyboards 'Alt' is labelled as 'Opt'` is added below the "Edit statements by" entry.
