### ISSUE TITLE
Duplicate up button

### ISSUE THREAD

**Issue by CatsAreFluffy** [expln/metamath-lamp#154]
It'd be nice to have a button to make a copy of a statement above that statement. You can already do this using expression selection, but that's slow for complicated statements.

**Comment by CatsAreFluffy** [comment]
The existing duplication operation is similar to what I'm proposing, but that leaves the original justification on the top copy, whereas duplicate up would leave it on the bottom copy.

**Comment by expln** [comment]
I plan to replace the existing "duplicate" button with two new buttons - one to duplicate down, another to duplicate up.

**Comment by expln** [comment]
This is ready on [dev](https://expln.github.io/lamp/dev/index.html).
