### ISSUE TITLE
When substituting, always use the most recent selections

### ISSUE THREAD

**Issue by CatsAreFluffy** [expln/metamath-lamp#155]
If I have a step selected, then if I try to select two fragments and substitute them, the substitution dialog uses the selected step and one of the fragments, which is pretty much never what I want. It'd be better if the substitution dialog always used the most recent selections, so in that situation it'd substitute the two fragments instead.

**Comment by expln** [comment]
This is ready on [dev](https://expln.github.io/lamp/dev/index.html).
