### ISSUE TITLE
Unable to manually add disjoints on mobile

### ISSUE THREAD

**Issue by BTernaryTau** [expln/metamath-lamp#164]
Adding a new line to the disjoints box currently requires pressing shift+enter, but this doesn't work on mobile devices. Pressing enter on a smartphone/tablet should insert a new line instead of exiting the text area.

**Comment by expln** [comment]
A fix is available on [dev](https://expln.github.io/lamp/dev/index.html). I added a new button. You may use it on mobile to start a new line, or to insert a line break in the middle of a text.

![image](https://github.com/expln/metamath-lamp/assets/47696142/aa7b9a6f-48bc-48f9-b783-3ea5a5e7de91)

**Comment by expln** [comment]
This fix is available in version [19](https://expln.github.io/lamp/v19/index.html).
