### ISSUE TITLE
Reorder variables in DV conditions

### ISSUE THREAD

**Issue by BTernaryTau** [expln/metamath-lamp#172]
It would be nice if class and wff variables always appeared at the beginning of distinct variable conditions, and if setvars were always in alphabetical order. This would match how mmj2 currently orders variables and help keep set.mm's formatting more consistent.

Currently there isn't an official convention for this, but there is some discussion about creating one (see https://groups.google.com/g/metamath/c/vRXuz7Qs5wY/m/eaxltrMsBwAJ and https://github.com/metamath/set.mm/pull/3573#discussion_r1362383185).

**Comment by expln** [comment]
This should not be difficult. I will implement this, hopefully in a few days.

**Comment by expln** [comment]
Reordering of variables in DV conditions is available on [dev](https://expln.github.io/lamp/dev/index.html). Variables are ordered by type and name. Ordering by type may be customized on the Settings tab by the "Sort disjoint variables by type" setting. It contains space separated list of types in the order which should be used in DV conditions. Omitted types will be placed at the end in DV conditions. By default, it is "class wff".

**Comment by expln** [comment]
Reordering of variables in DV conditions is available in [version 20](https://expln.github.io/lamp/v20/index.html).
