### ISSUE TITLE
Proposal (low priority): Renumber

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#18]
I propose adding a "renumber" option that renumbers steps. Hypotheses would be h1, h2, etc., while other steps would be 1, 2, 3, etc. (except for the last one).

**Comment by expln** [comment]
Yeah, I already had a plan to do this. I will do exactly as you proposed with an additional change - if a label contains at least one non-digit character then this label stays unchanged (that would mean a user renamed this statement manually and probably they want that statement to have such label). Please let me know if you think this doesn't make sense.

**Comment by david-a-wheeler** [comment]
That sounds *perfect*! Thanks!

**Comment by david-a-wheeler** [comment]
@expln - I worked on implementing renumbering last night, & I plan to send you a PR tonight with that addition to the tool. While it's not *vital*, it's nice to have... and you don't have to write any code to make it happen :-).

**Comment by david-a-wheeler** [comment]
I think this one is done!

**Comment by expln** [comment]
There is a new menu item in the editor `Rename hypotheses`. It will rename all the hypotheses in the editor according to this template `the goal step label` + `.` + `integer number starting with 1`.

**Comment by david-a-wheeler** [comment]
Awesome! I've been dealing with some personal issues that have rather distracted me. I intend to improve the tutorial to match (though of course feel free to add things yourself!).

**Comment by expln** [comment]
I thought that once the tutorial diverge from the latest version to much I will update it. But if you can update it, it will be great. I am also working on other small improvements. Thank you!
