### ISSUE TITLE
Error when '.,' appears in disjoints

### ISSUE THREAD

**Issue by BTernaryTau** [expln/metamath-lamp#199]
If a theorem has a variable with the name '.,' in a distinct variable group (such as ipffval), mm-lamp incorrectly interprets the comma as separating two variables and gives the error "The symbol '.' is not a variable but it is used in a disjoint statement."

<img width="1313" alt="image" src="https://github.com/user-attachments/assets/f93a6c91-ef29-45c1-aa1b-ec0559d8e3b8">

**Comment by zwang123** [comment]
Same happened here for `.+` and `.<_` in `prdsval`.

**Comment by expln** [comment]
Thank you for reporting this bug. It is fixed in the [dev](https://expln.github.io/lamp/dev/index.html) version of mm-lamp. The fix was to use spaces instead of commas as delimiters for variables in distinct variable groups. This however introduced a small breaking change. You'll have to manually replace commas with spaces in your active proof in mm-lamp in dev version.

**Comment by BTernaryTau** [comment]
Does this also apply to proofs imported from JSON or are those converted automatically when they are loaded?

**Comment by expln** [comment]
Yes, it also applies to proofs imported from JSON. To be honest I forgot about this use case. Looks like it is a problem if somebody stored a lot of proofs in the form of URL (which uses the same mechanism as importing from JSON). I will check if I can implement the automatic conversion. Thanks for reminding me about that use case.

**Comment by expln** [comment]
The automatic conversion has been implemented in the [dev](https://expln.github.io/lamp/dev/index.html) version. It works for all cases: importing from old JSONs, opening old URLs, switching from the old mm-lamp version to the dev one.

**Comment by expln** [comment]
The fix is available in [version 25](https://expln.github.io/lamp/v25/index.html).
