### ISSUE TITLE
Proposal: add Web link to iset.mm

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#2]
The tool currently lets you download set.mm from the web. I propose adding iset.mm (latest) as well. The iset database has multiple developers.

**Comment by expln** [comment]
Got it. The [change](https://github.com/expln/metamath-lamp/commit/2545fc968e8d65ad6428d1ff3ef3f4571f5c0682) is already in develop branch. It will be deployed with the nearest release. For now, as a workaround, it is possible to add this file manually on the settings tab.

**Comment by david-a-wheeler** [comment]
@expln -I don't see iset.mm listed in v11 as a web selectable option. Did that option get merged?

**Comment by expln** [comment]
Yes, it is on dev. If you don't see it in the dropdown, probably it disappeared from your settings. Please open settings tab, click "Restore default URLs" and "apply changes". It should appear again.

**Comment by expln** [comment]
@david-a-wheeler 

How do you think, will it be better if I make those settings less dynamic? I mean it will be impossible that `set.mm:latest` and `iset.mm:latest` are not listed in the dropdown. And also it will be impossible to change their URLs.

**Comment by expln** [comment]
I made it impossible for set.mm and iset.mm not to be listed in the dropdown.

**Comment by david-a-wheeler** [comment]
Great idea! One fewer ways to make a mysterious mistake :-)
