### ISSUE TITLE
Add a "reset" option (with "Are you Sure?")

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#21]
Once you're done with a proof, it's not clear how to restart from scratch. You can select and delete all the statements, but that doesn't load a different database. It'd be nice to have a "reset" button, which of course would ask for confirmation (default NO) before erasing everything.

**Comment by expln** [comment]
I can add a "reset" button but I am not sure that it should reset the database. As for me it will be much handy if this button removes all statements, all variables, disjoins, and description. But leaves currently loaded database untouched. 

Changing the database is very simple - click it (I mean click the header) and it will be expanded, then according to what you need either press the "trash can" button, or change the scope and label, add new sources if needed. Then press "Apply changes".

The reason why I think it doesn't make sense to reset the database is how I imaging a usual workflow - load a database, create a proof; delete the proof, create another proof; an so on. With resetting the database users will be forced to load a database again after creating each proof.

**Comment by david-a-wheeler** [comment]
Okay, that makes sense! Maybe "Are you sure?" dialogue can make that clear. Something like this:

> Note: Resetting will erase individual proof information such as the description, variables, and any proof steps. Resetting does *not* change the current context, that is, the set of loaded databases and their scope. To change the context, go to the context section at the top, modify the context, and press "Apply changes".

**Comment by david-a-wheeler** [comment]
BTW, I've worked out a simple solution in the editor: use loading. E.g.:

**[Start up the metamath-lamp application in a completely empty state (erasing whatever you had before in metamath-lamp)](https://expln.github.io/lamp/latest/index.html?editorState=eyJzcmNzIjpbXSwiZGVzY3IiOiIiLCJ2YXJzVGV4dCI6IiIsImRpc2pUZXh0IjoiIiwic3RtdHMiOltdfQ==)**

**Comment by expln** [comment]
Unfortunately this will not work in the next version. Just try to replace `latest` with `dev` in this URL and you'll see that mm-lamp opens in TEMP mode. If this approach worked it would be very easy to accidentally erase current editor state just by navigating to another URL (to see some example, or if somebody shared a proof with you and you want to check it in the middle of creating of your own proof). 

TEMP mode is read-only. Any change you do in TEMP mode is not saved and will be lost when you close a browser tab with it. This relates to both changes in the editor and in the settings.

Currently there is no easy way how to move from TEMP mode to NORMAL mode. The only way is to 1) use `export to JSON` in TEMP mode; 2) open a new tab with mm-lamp in NORMAL mode; 3) use `import from JSON`.

I will add a warning for users when they start editing in TEMP mode, reminding that all their changes will not be saved in this mode.

**Comment by expln** [comment]
A warning about editing in TEMP mode is implemented on dev. Open mm-lamp on dev by some URL with editorState and try to edit anything in the editor - you will see this warning.

**Comment by david-a-wheeler** [comment]
Can you tell me more about TEMP mode? What is different t about TENP mode? How do you enter and leave it?

**Comment by david-a-wheeler** [comment]
Also, what indicates TEMP mode? Just the browser header? The browser header is not normally shown on Firefox on Android, and I don't think it's shown on Macs either.

**Comment by david-a-wheeler** [comment]
Ah!! *Now* I see it when I try to *edit* an existing statement:

> Editing in TEMP mode
> You are about to edit in TEMP mode. All changes you do in TEMP mode will be erased upon closing current browser tab. If you want to continue editing in NORMAL mode, please do the following actions: 1) use "Export to JSON" to copy current editor state to the clipboard; 2) open a new tab (or switch to an already opened tab) with metamath-lamp in NORMAL mode; 3) use "Import from JSON" to load the copied editor state from the clipboard.

However, I don't see this warning when I press "+" (add statement). Shouldn't this warning also show up the first time you use any modification like add, duplicate, search, replace, renumber?

It looks like "TEMP mode" is forcibly enabled when you load from a URL, correct? That's a little unfortunate for me, because for a tutorial it's nice to be able to reload a specific known state. It'd be nice if there was a way for the URL to say "use this as the real thing" (presumably requiring user confirmation first). I like the idea of a TEMP mode though.

Here's my attempt to explain it, please let me know if this is correct or incorrect:

**OLD TEXT**

This menu includes several ways to export and import your
current state:

* "Export to URL": Provides a URL. You or anyone else
  can use this URL to re-open the proof assistant at
  this current state.
* "Export to JSON": Provides the current proof assistant
  state as text; you can save this where you wish.
* "Import from JSON": Allows you to load a state previously
  exported with "Export to JSON". 

**NEW TEXT**

This menu includes several ways to export and import your
current state.

You can save your state for reloading later in a JSON format (if you store these in a file they conventionally have a `.lamp.json` suffix):

* "Export to JSON": Provides the current proof assistant
  state as text; you can save this where you wish.
* "Import from JSON": Allows you to load a state previously
  exported with "Export to JSON". 

You can also export to a URL using "Export to URL". If you or anyone else opens this URL, Metamath-lamp is opened in "TEMP" (temporary) mode. TEMP mode is intended to let you view others' work without erasing your own; any changes in TEMP mode won't affect your existing work in your "normal" editing page and any changes you make in TEMP mode will be discarded when you leave the page. To warn your of this, the web page header starts with "TEMP", and the first attempt to edit will remind you that you're in TEMP mode and that changes will be discarded later. There's currently no mechanism to switch from TEMP mode to regular mode. If you want to save results from TEMP mode, use "Export to JSON" and record the results somewhere; you can then use "Import from JSON" to load the results into a normal tab.

**Comment by david-a-wheeler** [comment]
My attempt to explain TEMP mode is here, please correct as needed:
https://github.com/metamath/lamp-guide/pull/96

**Comment by david-a-wheeler** [comment]
Related: https://github.com/expln/metamath-lamp/issues/114

**Comment by expln** [comment]
> Can you tell me more about TEMP mode? What is different about TEMP mode? How do you enter and leave it?

You've understood it correctly.
The main purpose is not to erase user's work accidentally.
You've also wrote correct instructions in the guide on how to exit TEMP mode (via "export to / import from" JSON).
As of entering, it is also not much convenient but possible: just export to a URL and open this URL :) Yeah, this doesn't work for big states. But if you need to do some experiment without modifying your current state and URL is not enough, you may open a new incognito tab. It has different local storage.

> Also, what indicates TEMP mode? Just the browser header? The browser header is not normally shown on Firefox on Android, and I don't think it's shown on Macs either.

For now yes. But I will improve it in scope of https://github.com/expln/metamath-lamp/issues/117

> However, I don't see this warning when I press "+" (add statement). Shouldn't this warning also show up the first time you use any modification like add, duplicate, search, replace, renumber?

You are right, I missed these cases. I will handle them too. Thanks for pointing this out.

> It looks like "TEMP mode" is forcibly enabled when you load from a URL, correct? That's a little unfortunate for me, because for a tutorial it's nice to be able to reload a specific known state. It'd be nice if there was a way for the URL to say "use this as the real thing" (presumably requiring user confirmation first). I like the idea of a TEMP mode though.

Correct, that's how it works now. I implemented TEMP mode even before your first PR in this repo, I didn't expect this need :) Let's discuss this in the corresponding issue you've created https://github.com/expln/metamath-lamp/issues/114
(For now, I am going to release v11 with how it works now)

**Comment by david-a-wheeler** [comment]
> (For now, I am going to release v11 with how it works now)

Absolutely! My goal right now is to document it correctly & file issues for my ideas on how I think it could be improved in the future.

**Comment by expln** [comment]
The "Reset editor content" menu item in the hamburger menu is available on dev. There is no "Are you sure?" because users can use the undo/redo feature.

**Comment by david-a-wheeler** [comment]
Great!!

Omitting "are you sure", because of undo/redo, is just fine. Having undo eliminates all sorts of problems :-).

**Comment by expln** [comment]
This is available in [version 16](https://expln.github.io/lamp/v16/index.html)
