### ISSUE TITLE
Enable all features on Smartphones - don't require alt-left click (aka opt-left click)

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#25]
Metamath-lamp is *surprisingly* functional on smartphones. However, there is no "alt-left click" on typical smartphones. I propose adding some mechanism so that users who can't (easily) do alt-left click can still access all of metamath-lamp's functionality.

I propose adding two more buttons on the toolbar:
* "S" - Select statement fragments. When this is selected, the cursor changes, and you can pick a statement, which immediately opens like alt-left click & lets you keep selecting statement fragments. Use circled X, or this "S" again, to leave the mode.
* "H" - "Hypothesis Toggle" - Only works when 1+ statements are selected; those statements are toggled between "hypothesis" or not.

Feel free to implement it some better way. At the least, being able to *create* hypotheses is key for creating proofs on smartphones, but simplifying statement fragment handling is also very nice on smartphones.

The only other issue on smartphones that I found is that smartphone touchscreens don't have "hover". To address that, see #23. In short, long-downpress could also show the hover text (but make sure the pressing finger doesn't cover the text!).

**Comment by david-a-wheeler** [comment]
I think this is ready-on-dev, yes?

**Comment by expln** [comment]
Yes, that's ready-on-dev. Just for the future reference - https://github.com/expln/metamath-lamp/issues/97
