### ISSUE TITLE
Tweak default of "add statement" to insert just before last statement

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#29]
The worked example for 2+2=4 convinces me that the current default for "add statement" is wrong when no statement is selected. If no statement is selected and there's at least one statement, the new statement should be added *just* before the last statement. As long as you add the goal first (as recommended) this is the most likely place that the user wants a new statement added.

Currently I believe the default is to add the statement as the *last* statement. That is usually the right thing to do, but for a prover (like this) I think it's not the best default.

Making this change to the default will make the tool easier to use *and* easier to explain. It would, for example, eliminate a lot of steps in the 2+2=4 example.

**Comment by david-a-wheeler** [comment]
PS: If someone wants a statement at the end, they can always add it and move it down. But I think wanting to add a new statement to the very end is an unusual event.

**Comment by expln** [comment]
2+2=4 example convinced me too that this should be improved. I don't want to hardcode this automation, so I am planning to fix this issue (and another - #10 ) by adding two new settings:

1. "Initial statement label"
- description: when you add a new statement and there are no other statements in the editor, this will be the label for the statement;
- default value: qed
2. "Always move statement labeled as [     ] to the bottom"
- description: if there is a statement labeled as specified by this setting, this statement will be kept at the bottom.
- default value: qed

Maybe settings look unusual but this should fix the issue. Setting them to an empty value will disable this automation and the editor will work as it works now.

**Comment by david-a-wheeler** [comment]
The problem with this approach is that if you rename the goal statement label, it quietly doesn't go to the end.

Here's an alternative: Instead of "H" or "P", have 3 types: "H", "P", or "G" (goal). A "goal" is a P-type that is kept at the bottom. If you set any other statement to the goal, any other goal is changed to "P".

**Comment by david-a-wheeler** [comment]
Note: This is related to #10

**Comment by expln** [comment]
What do you think about instead of G statements, adding a boolean attribute for each statement "stick to the bottom"? This way more than one statement could be kept at the bottom (if needed).

**Comment by david-a-wheeler** [comment]
"Stick to the bottom" is okay.  Presumably if more than one sticks, then they'd stay in the same order. The problem is showing that status - it'd stick to use up valuable horizontal real estate.

As an alternative, you could use my "G" (goal) idea. However, instead of having "stick to the bottom" semantics, it would simply affect the *default* location when you add a new statement and no statement is selected. That way, you can move statements around to your heart's content, including moving statements after qed (e.g., if you think you don't want to use them but aren't sure).

**Comment by expln** [comment]
Ok. Currently G statements look more promising for me. I will analyze the problem a bit more and either implement something or return with more questions.
