### ISSUE TITLE
By default ignore any statements marked (New usage is discouraged.)

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#31]
By default searches, unifications that add statements, and bottom-up proofs should skip any statement (an axiom or theorem) with a comment that includes the text "(New usage is discouraged.)". This should be a checkbox in "Settings":

(Checkbox) Ignore statements marked with "(New usage is discouraged.)"
(default checked).

If a user hand-adds such statements (say in a justification or as a root of a bottom-up search) then that's fine, and it shouldn't *remove* them. The point is that the tool should not be automatically adding or reporting them by default.

**Comment by expln** [comment]
This is partially implemented, but it is not so convenient as you proposed. Could you please review (if not already) the existing feature if it resembles what you described? starting at 2:30, ending at 3:45 in this demo https://drive.google.com/file/d/1haJff_AN1M6HZGrWXsgqzrxq-Di84gmZ/view?t=150

What I am going to change:

1. Add a new setting as you suggested. But it will be not a check box. It will be a regex with an appropriate default value (to skip what you suggested).
2. Both existing setting "Assertions to skip" and the new one will be merged (I mean the sets of assertions produced by them will be merged).
3. Currently usage of a discouraged assertion is a critical error not allowing to proceed. I will change it to a warning so users will see there is a potential problem but they still can work.
4. Currently discouraged assertions are not appearing anywhere including search and bottom-up proofs. I will add a check box to these places "allow discouraged assertions" so users may use them if they wish.

**Comment by david-a-wheeler** [comment]
The feature described at 2:30 is somewhat similar. However, since discouragement is usually marked in a database with a special comment, I think it's more important to at least directly support that.

Using a regex is definitely more flexible. Having a way to control which statements are considered discrouaged, *and* control the text used to infer that a statement is discouraged, would certainly do I what I'd like! I think it's important that the default be the exact text sequence already used in set.mm/iset.mm, and that it be enabled by default. Once that happens, proofs won't accidentally use discouraged statements.

There *are* cases where you *want* to use a discouraged statement, so I would not make that an error. However, it should require an *express* selection by the user. Having a checkbox on search and backwards proof to allow them, but skipping them by default, would make that easy. Thanks!

**Comment by david-a-wheeler** [comment]
We definitely also want to ignore syntax axioms with "new usage is discouraged" - the current fragment selector gets confused because of this :-).

**Comment by expln** [comment]
Sure, it is also mentioned here https://github.com/expln/metamath-lamp/issues/108

**Comment by expln** [comment]
This is implemented on [dev](https://expln.github.io/lamp/dev/index.html).

Four new settings were added on the Settings tab:
1. Regex to determine discouraged assertions by description
2. Regex to determine discouraged assertions by label
3. Regex to determine deprecated assertions by description
4. Regex to determine deprecated assertions by label

The first two settings are used to specify discouraged assertions.
The third and the fourth settings are used to specify "deprecated" assertions. They were added to implement another issue https://github.com/expln/metamath-lamp/issues/152

If any of these settings is empty it means the setting is not set, and it is not used.

Based on these four settings, each assertion gets assigned three boolean flags:
- `discouraged` - all assertions which match the first or the second regex;
- `deprecated` - all assertions which match the third or the fourth regex;
- `transitively deprecated` - all theorems which depend on any of `deprecated` assertions;

Under the four new settings on the Settings tab, there is a table with 6 checkboxes which define which kinds of assertions are allowed to be used in which kinds of proofs. This table also contains colors to highlight assertions of corresponding types in proofs.

If mm-lamp finds that some assertion is used in a proof, but it is not allowed by these new settings then mm-lamp will not fail, neither block the UI. It will continue working as usually. However, all such assertions are highlighted with different colors, so users can notice them. This is up to the user to eliminate unwanted assertions from existing proofs. But in new proofs found by mm-lamp, unwanted assertions will not be used.

The four new settings on the Settings tab define defaults. But it is possible to overwrite them in the bottom-up prover dialog.

The Explorer tab allows to find assertions of all the three kinds mentioned above.
