### ISSUE TITLE
Implement undo/redo

### ISSUE THREAD

**Issue by expln** [expln/metamath-lamp#33]
The editor has to provide possibility to return to one of few previous states. The number of kept previous states may be not too big, due to limitations of browsers. 

Known workaround:
If you know that the next action may produce unwanted results, you may use "export to json" to save editor state before that action. "export to json" feature is available in the top right corner menu on the editor tab. You also may include current timestamp to the json text before copying. This will help to navigate between such stored states if you have many of them stored in a file. In order to restore a state, use "import from json" feature available in the same menu. Don't put the timestamp when restoring, if you saved it previously, only json data should be put into the "import from json" dialog. This is a temporary solution until undo/redo is implemented.

**Comment by david-a-wheeler** [comment]
Note: The internal undo/redo could be implemented by storing the equivalent of what export/import to JSON processes.

**Comment by david-a-wheeler** [comment]
Note: I would first implement undo/redo by storing the full state before changing anything in it. That may be fast enough for all. If not, it could be optimized by storing deltas of a few common cases (e.g., edit a step, add a step, delete a step,). Proof-wide replacements are probably OK as full edit state stores, and full edit state stores are trivial to implement and have fewer errors prone cases.

**Comment by expln** [comment]
I am planning to use a mixed approach - try to store deltas first, but if changes are too big then store entire state. There are very small changes, so saving the full state doesn't make sense. But I will start implementing and check how it works. If this is too difficult to implement I will switch to storing the full state always.

**Comment by expln** [comment]
> There are very small changes, so saving the full state doesn't make sense.

Of course it makes sense to store the full state. I just meant that this may be inefficient, for example, in the case when there are 20 steps and a user moves one statement from the bottom to the top.

**Comment by david-a-wheeler** [comment]
I was just thinking about things from an implementation point-of-view. If you have to store full state *sometimes* then the first cut can simply always store/retrieve full state for undo/redo. You can then optimize specific cases until performance (speed & memory use) is good enough, e.g., optimize worst cases or most common cases. Storing full state is going to be generally much less efficient than storing a delta (e.g., moving bottom to top), but the inefficiency may not matter much.

**Comment by expln** [comment]
That's definitely makes sense. Maybe I will do this way. I will check.

**Comment by expln** [comment]
The undo/redo feature is deployed to dev. How it works and looks currently is its final state. However, comments and suggestions are very welcome. I am also going to improve its performance a bit (I think it will not be noticeable, but still there is what to improve) and write few more tests.

Here is a short description:

* Undo/redo is launched by a new icon button - "Restore previous state". Ctrl+Z is not implemented. That will be another change, where I will implement other shortcuts too. But this will not be very soon.
* Once this new button is clicked a popup dialog is opened. It is opened in a fullscreen mode, so it doesn't look like a dialog.
* In this dialog, you may click `< PREV` button to go to the previous state and `NEXT >` button to go to the next state. Click the `Restore this` button to load currently shown state to the editor. Click `Close` button to close the undo/redo dialog. When the `Restore this` button is disabled that means the current state is shown, so nothing to restore. The undo/redo dialog always opens on the state previous to the current state. The ability to show current state in the dialog is not required for undoing and/or redoing, but it was added to make it possible to switch between the current state and the previous one back and forth to see the changes visually.
* The change history is stored to the local storage upon each change in the editor. Therefore, a too long history may affect performance. There is a new setting "Max length of editor history". By default, its value is 20. I didn't do any experiments or calculations to determine this number. I checked that it works well on my computer. And I think that storing 20 previous states (actually only current state is stored and others are represented by differences) should be more than enough to recover from any unintentional bad change. So, main purpose of the current implementation of the undo/redo is to recover from accidental unwanted changes. For storing some key states of the editor please use the export to JSON and save such JSONs somewhere in a text file.
* A new text field "Description" is added to the "Export to JSON" dialog. It allows to write some short description of the state being exported. Pressing `Enter` in this field copies the state to the clipboard and closes the dialog.
* Change histories for the regular mode and the TEMP mode are stored separately. This also solves one issue with the TEMP mode - if the app crashes it is still possible to restore latest changes from the history (if the crash is not caused by storing/reading the history from the local storage :) ).

**Comment by david-a-wheeler** [comment]
This is very cool! The icon is perfect and the back/forth looks nice.

It's easy to get "lost" of in terms of "what is the state being displayed?" I have a thought: between "previous" & "next", have [ NUMBER ] which shows the offset from current state, e.g., "-1" for one interaction back, "-2" for two back, etc.

You probably don't need to support 20 back; 10 is probably plenty. But if you can support it, sure why not?!

On my smartphone there is *no* more room using Chrome for any more icons, even with compact mode and small buttons. Even clicking on the hamburger is enough to cause 2 lines. The editor icon bar requires 2 lines on Firefox (ugh), which is definitely not ideal (the icons seem to take a little more room on Firefox). It'd be great if commands could overflow into the hamburger once the icons run out of room.

**Comment by david-a-wheeler** [comment]
Also - my first thought was to give "relative" position (e.g., -1 from current state). But relative position can be harder to visualize. Maybe it'd be better to just count the number of actions a user takes (e.g., from load or start), and show as your 'current position" the count of actions (making the position an *absolute* position). Bonus points if you store the "count of actions" in the JSON file, for later reloading :-). That would make it easier to understand "which state am I accepting?"

**Comment by david-a-wheeler** [comment]
> Bonus points if you store the "count of actions" in the JSON file, for later reloading :

I take it back, the count should start from 0 whenever you begin or reload. Otherwise, people may be tempted to do a code golf where you minimized the number of actions. They may also expect the tool to save previous states in the json file, which seems excessive to me.

**Comment by david-a-wheeler** [comment]
Also: When viewed on a smartphone, it can break badly. On my phone "< Prev" is the last on the line, followed by "Next >" on the following line.

I suggest grouping `<< Prev COUNTER Next >>` so that if they don't all fit on a line, they begin the next link. In HTML I'd use non-breaking spaces between those parts; I don't know what you do in React, but I presume there's a way to do it.

**Comment by david-a-wheeler** [comment]
It's not always obvious what steps have changed between versions. It might be nice in a future version to highlight a step that's different from the next step. But I don't think that's worth delaying a release, it's something to think about for the future as a possibility.

The main issue is that now people can experiment without fear. That's a powerful capability, especially when they're starting out with a tool.

**Comment by david-a-wheeler** [comment]
> A new text field "Description" is added to the "Export to JSON" dialog. It allows to write some short description of the state being exported. Pressing Enter in this field copies the state to the clipboard and closes the dialog.

I like the idea, but having 2 different things called "description" is confusing. Can you call this something else, like "notes"?

**Comment by expln** [comment]
> This is very cool! The icon is perfect and the back/forth looks nice.

Thanks!

> It's easy to get "lost" of in terms of "what is the state being displayed?" I have a thought: between "previous" & "next", have [ NUMBER ] which shows the offset from current state, e.g., "-1" for one interaction back, "-2" for two back, etc.

I agree, showing relative position might be handy. The very first version of the undo/redo used the Pagination component, so it showed relative position and also allowed to jump quicker between versions. But it showed positions in inverse order, so I replaced it with just two buttons. But the idea of showing relative position still makes sense, so I will add it as you proposed, but numbers will be positive - 0 for current state, and 1,2,3 for respectively one interaction back, two back, three back etc. I think this should be clear enough for users.

> You probably don't need to support 20 back; 10 is probably plenty. But if you can support it, sure why not?!

I will test with 20 and 10 and compare.

> On my smartphone there is no more room using Chrome for any more icons, even with compact mode and small buttons. Even clicking on the hamburger is enough to cause 2 lines. The editor icon bar requires 2 lines on Firefox (ugh), which is definitely not ideal (the icons seem to take a little more room on Firefox). It'd be great if commands could overflow into the hamburger once the icons run out of room.

Unfortunately this is not a quick fix. I will respond in more detail in the issue you've submitted - https://github.com/expln/metamath-lamp/issues/134

>Also: When viewed on a smartphone, it can break badly. On my phone "< Prev" is the last on the line, followed by "Next >" on the following line.
>I suggest grouping << Prev COUNTER Next >> so that if they don't all fit on a line, they begin the next link. In HTML I'd use non-breaking spaces between those parts; I don't know what you do in React, but I presume there's a way to do it.

I noticed this on my phone too. I like your idea to group these buttons, will do that.

> It's not always obvious what steps have changed between versions. It might be nice in a future version to highlight a step that's different from the next step. But I don't think that's worth delaying a release, it's something to think about for the future as a possibility.

The app stores changes in the form of differences, so technically it should not be too hard (however, there are some tricky moments related to merging small changes). But I gree with you that highlighting may be done later.

> having 2 different things called "description" is confusing. Can you call this something else, like "notes"?

Thanks for pointing this out. Sure, I will rename it. "Notes" seems reasonable.

Thanks for as always constructive feedback!

**Comment by expln** [comment]
This feature is released in version 14 https://expln.github.io/lamp/v14/index.html
