### ISSUE TITLE
Add reccot example to guide

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#36]
The guide should eventually have several worked examples so that people can learn from them.

The reccot example from here:
https://drive.google.com/file/d/1haJff_AN1M6HZGrWXsgqzrxq-Di84gmZ/view?t=150
should eventually be added as one of those worked example.

NB: It'd be better if it started loading "up to but not including" reccot. That is much easier to explain, and works no matter how set.mm is reorganized.

**Comment by expln** [comment]
The video you referenced doesn't include reccot example. My latest video with reccot is this one - https://drive.google.com/file/d/1IwdHLpQreZ_1CJFZJmptRJc2unO8aNh4/view

**Comment by david-a-wheeler** [comment]
Done.
