### ISSUE TITLE
Include description as a comment in the generated proof

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#38]
When there's a generated proof, just before the goal statement's id include "$(" then the description text then "$)".

Metamath databases generally *always* have a description of each proven statement, it's odd to not include the description here in the generated proof. Currently a user has to copy-paste and recreate the descriptive comment, for no obvious reason.

**Comment by expln** [comment]
This is implemented on dev.

Previously I didn't understand why this is important, but now I see it may be handy when https://github.com/expln/metamath-lamp/issues/45 is implemented.
