### ISSUE TITLE
Add "paste" to edit fragment selector dialogue (easy win!)

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#42]
There's already a "copy" button in the edit selector dialogue. It'd be *really* convenient if there was also a "paste" button that did the equivalent of control-V / command-V; it would be sensibly placed next to copy.  It should work *even* if you're not currently in edit mode (basically it'd do the equivalent of push edit button, control-V, Return).

**Comment by david-a-wheeler** [comment]
Also: make "paste" (including control-V) when you have a region selected and it is not in edit mode. That would make copying and pasting syntax-selected things more convenient.

**Comment by david-a-wheeler** [comment]
I'm going to try to implement this. It'll take me much longer than you, but I'm hoping to learn some things along the way.

**Comment by expln** [comment]
To make things a bit easier. In MM_cmp_user_stmt:
* rndSelectionButtons() - this is the place to add the new button for pasting
* getSelectedRange() - this functions determines what part of a statement is selected (this is needed to know what part of a statement should be cut out and replaced with the content from the clipboard)
* Invoke onContEditDone("new text") to propagate changes from MM_cmp_user_stmt to MM_cmp_editor.

**Comment by expln** [comment]
@david-a-wheeler 

I deployed your changes to dev. Please check how it works for you. If it is good then I will release it.

I also had to do a small change in how promises are handled in the new code. This is strange, but locally everything worked well, but when I built it (prepared a production ready optimized version of scripts) it failed with an error "Uncaught ReferenceError: exports is not defined". I don't know what happened. But my [change](https://github.com/expln/metamath-lamp/commit/39c57274daec52c3fb137d0bad2ac1ad69ca1a06) fixed this error - I replaced await with promiseMap.

**Comment by david-a-wheeler** [comment]
Thanks! I did some quick checks on the current development version here:

https://expln.github.io/lamp/dev/index.html

On Firefox "paste" does nothing. I opened up its developer tools and looked at its Console reports, which said:

> MM_react_common.bs.js:26:29
>
> Uncaught TypeError: navigator.clipboard.readText is not a function
>    readFromClipboard MM_react_common.bs.js:26
>    onClick MM_cmp_user_stmt.bs.js:1002
>    React 11
> 10 MM_react_common.bs.js:26:29
>    readFromClipboard MM_react_common.bs.js:26
>    onClick MM_cmp_user_stmt.bs.js:1002
>    React 11

When I tested the website using Chrome I had a dialogue pop up I haven't seen before:

> expln.github.io wants to
>
> (paste symbol) See text and images copied to the clipboard
>
> Block Allow

When I clicked on "Allow" it worked. While I didn't expect the dialogue, it seems perfectly reasonable & fine behavior on Chrome.

I'd prefer it worked on multiple browsers, but I don't know why it currently doesn't.

**Comment by david-a-wheeler** [comment]
I tried to find some more information, and ended up here:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

It appears that FIrefox *does* support readText from the clipboard. However, you're supposed to request such access:

> The Clipboard API writes arbitrary data to the clipboard from your extension. Using the API requires the permission "clipboardRead" or "clipboardWrite" in your manifest.json file. As the API is only available to Secure Contexts, it cannot be used from a content script running on http:-pages, only https:-pages.

**Comment by david-a-wheeler** [comment]
RELEASE THIS VERSION.

I've tracked down the problem. It's a Firefox-specific issue. The problem is that the current version of Firefox doesn't support reading from the clipboard (using readText) the "new" way.

Sources:
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility
this is confirmed with:
https://caniuse.com/mdn-api_clipboard_readtext

I propose releasing this as it is, and noting in the documentation that "paste" functionality doesn't work in versions of Firefox up through at least version 117. Users of Chrome or Safari will have new functionality, and Firefox users will be no worse off.

There is an old deprecated approach for getting the clipboard using execCommand. Firefox *does* support that. In the long term we could implement shim code that uses the old approach if the new approach fails:
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

There's a polyfill we could bring in to do this. Some discussion here:
https://www.techiedelight.com/copy-text-to-clipboard-javascript/

Anyway, I suggest shipping it now, and we can then discuss if we want to do workarounds to make it work on Firefox.

**Comment by david-a-wheeler** [comment]
Sigh, "paste" was supposed to be *easy* :-).

The fundamental problem is that [Firefox supports clipboard writeText but not readText](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility). The deprecated approach requires some extreme weirdness, too.

So I propose the following: in `src/metamath/ui-utils/MM_react_common.res` create a reference to a "backupClipboard" string (`let backupClipboard = ref("")`). If the browser doesn't have `navigator["clipboard"]["readText"]` defined, it'll save and read from backupClipboard instead. When writing (copying to clipboard) it'll always write to the clipboard (*everyone* supports writing to the clipboard). That means copying & pasting inside the app will work everywhere, even on Firefox. Copying to clipboard will also work. Pasting from the clipboard won't work, but that doesn't work for anything so it's no different. For most users that means it'll "just work".

**Comment by david-a-wheeler** [comment]
Here's a PR that implements a workaround for Firefox:

https://github.com/expln/metamath-lamp/pull/131

With this PR, copy & paste work continue to work on Chrome, but they also
work with Firefox as long as you stay within the application. "Copy to clipboard" works
fine on Firefox; on Firefox, "paste from clipboard" will only use an application-local
clipboard instead of the global clipboard. That's still a huge improvement, because
it means that selecting fragments and pasting them elsewhere becomes easy.

**Comment by david-a-wheeler** [comment]
I've tested the development version with Chrome and Safari; copy & paste works well.

Once I added PR https://github.com/expln/metamath-lamp/pull/131 then Firefox also seems to work well as long as the copy and paste is within the app (copying out the clipboard works fine, pasting from the clipboard external to the application is known to not work). So if you're willing to add https://github.com/expln/metamath-lamp/pull/131 then paste should work for all major browsers in use today.

Adding paste was certainly *not* as easy a win as I expected. It's sure nice, though. Having syntax-aware selection for copying and pasting makes it easier to correctly handle complex expressions.

**Comment by expln** [comment]
The corresponding PR #131  is merged and the changes are deployed to dev. Please, check that it works good for you. I will release it soon.

**Comment by david-a-wheeler** [comment]
I just tested dev on Chrome and Firefox (both on Android). It works well. Chrome give me an allow/block dialogue on first use, but it's really clear what's going on and I already documented that as a possibility.

I think it's ready to ship!

**Comment by expln** [comment]
Thank you very much! I've just recently released it - https://expln.github.io/lamp/v13/index.html

**Comment by david-a-wheeler** [comment]
Congrats on the release! Feel free to announce it. If you don't, I plan to.

**Comment by expln** [comment]
Thanks! I planned to collect more changes to announce, but, of course, waiting is not required. If you want to announce please feel free to do that.

**Comment by expln** [comment]
I see you've announced it. Thank you! I am closing this issue.
