### ISSUE TITLE
Add a way to easily see guide (and maybe repo page)

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#44]
It'd be good if there was a link that automatically opened a new tab to the guide (and maybe to the metamath-lamp home page). That way, users could quickly get more information without hunting.

**Comment by david-a-wheeler** [comment]
This is a duplicate of #72. I propose closing this one, #44, and keeping #72.

**Comment by expln** [comment]
I agree. Closing this issue.
