### ISSUE TITLE
Confusion about top-down

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#46]
@icecream17 noted confusion with terms like "top-down" in #28. Maybe we should use teems like "forward towards goal" and "backwards from goal'".

**Comment by expln** [comment]
I think "top-down" and "bottom-up" might be quite confusing. Usually I just skip these terms in a text and try to understand meaning from the context. What @david-a-wheeler proposes seems better to me. However, I would make it shorter - "forward proof" (going from hypotheses though a proof to the goal) and "backward proof" (going from the goal through a proof to the hypotheses) - when I read these terms I immediately understand what they mean. These may be used as "proving forward" and "proving backward" as well if needed.
