### ISSUE TITLE
On H/P dropdown, start selection at current state

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#55]
When pressing alt+left click on the **P** or **H**, it shows a mysterious dropdown with no indication of what it is. It'd be better if this dropdown automatically opened and started by highlighting the current value. That would make easier to see what it currently is, easier to change, and easier to see what the options are in the first place :-).

**Comment by expln** [comment]
The corresponding PR #132  is merged and the changes are deployed to dev. Please, check that it works good for you. I will release it soon.

**Comment by david-a-wheeler** [comment]
It works well on my tests. I think it's ready to ship.

**Comment by expln** [comment]
Thank you! I've just recently released it - https://expln.github.io/lamp/v13/index.html

**Comment by expln** [comment]
I am closing this issue. Thank you!
