### ISSUE TITLE
Enable visualization per justification, instead of a global setting

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#56]
Currently visualization is a global setting, which is less flexible.

Instead, when a justification is shown, add a dialogue to the right to enable or disable visualization of *that* justification. Then you can enable visualizations of some justifications and not others. Also, it makes the option visible "when you might use it" - the visualizations only make sense when you're showing a justification.

You might have a setting to set the *default* value of a visualization, that is, when you show a justification, should it be visualized or not by default? That would have a similar effect, but would also be more flexible.

**Comment by expln** [comment]
Would the below be a good enough implementation, how do you think?

- by default all visualizations are off
- each justification has a small button which turns on/off a visualization only for this justification
- Instead of the global menu item "Visualization is On/Off" there is another global menu item "Hide all visualizations" which will turn off all opened visualizations

**Comment by david-a-wheeler** [comment]
I love it!

The visualizations are a really distinctive capability of the tool. At first I just thought they were just window dressing, but I'm realizing that they are a real asset to a new user. I think this added control would be great.

**Comment by david-a-wheeler** [comment]
I think this issue can be closed, this ability is now in the develop branch.

**Comment by expln** [comment]
Yes, that's implemented. Just a short description:

* by default all visualizations are off
* each justification has a small button which turns on/off a visualization only for this justification.
* if justifications are always shown, then the same mechanism which is used to show/hide a justification now shows/hides a visualization.
* there is a global setting "Show visualizations by default" which works exactly as requested - "when you show a justification, should it be visualized or not by default?"
