### ISSUE TITLE
Problems editing parentheses (and other paired characters) (low priority)

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#64]
Currently when you edit and you press "left parenthesis", the tool adds "right parenthesis". This makes sense in some contexts, but it's annoying in others - in many cases you are *certain* to need to delete the right parenthesis, and their insertion is more trouble than help.

I think using them should be an editor setting (on/off), so if you hate them they stop getting added.

If it's on, it'd be nice if they were inserted using a smarter algorithm. Here's a simple one (algorithm 1):

> Insert the matching closing "paren" after the opening *if* the expression is at the end *or* the expression is followed by a closing "paren-like" symbol.

Algorithm 1 is at least simple to simple to implement.

Another algorithm (algorithm 2) would be:

> only add the right paren after the left one if the whole statement would be syntactically valid (once the "(...)" expression was completed).

However, this second one is complicated, I'm not sure how to do that quickly & I doubt it's worth the trouble.

**Comment by david-a-wheeler** [comment]
The *easy* solution is to just add a setting to enable/display smart parentheses. Then people like it, they can use it, otherwise they can turn it off.

**Comment by expln** [comment]
I am thinking of implementing the following:
- when you edit a statement, near the text field, there is a button to turn on/off parenthesis autocompletion. So you don't have to move your mouse too far. Also it should be possible to turn it on/off with a keyboard shortcut.
- There will be a global setting on the settings tab to indicate how you want this autocompletion to be (on or off) when you start editing a statement. So depending on what you do more often (editing existing or adding new) you may change this global setting.

**Comment by david-a-wheeler** [comment]
Cool! That would be nice.

**Comment by expln** [comment]
@david-a-wheeler

This is implemented on dev. However, not exactly as I planned:

* when you edit a statement, near the text field, there is a button to turn on/off parenthesis autocompletion. So you don't have to move your mouse too far. Also, it is possible to turn it on/off with the keyboard shortcut Alt+P.
* There is no a global setting to indicate how you want this autocompletion to be (on or off) when you start editing a statement. Instead, the last used state (on or off) is used when you start editing another statement.

This was easier to implement (no need to add a new global setting) and, as for me, it is convenient as well.

**Comment by david-a-wheeler** [comment]
Overall that's fine, but I recommend *NOT* using "Alt-P", as that usually means "print". Is "Alt+(" a possibility?

**Comment by expln** [comment]
As I know "Ctrl+P" means "print". What browser do you know where "Alt+P" means "print"? 
I thought about "Alt+(", but it would actually be "Alt+9", that's why I didn't want to use this shortcut.

**Comment by david-a-wheeler** [comment]
Nevermind, you're right, wrong meta key. Control-P is print on Windows, command-P on Mac, which isn't Alt-P or Opt-P.

**Comment by david-a-wheeler** [comment]
So carry forth, your current plan makes sense to me!

**Comment by expln** [comment]
This is available in version 15 https://expln.github.io/lamp/v15/index.html
