### ISSUE TITLE
Please move the metamath-lamp guide to the Metamath repo

### ISSUE THREAD

**Issue by expln** [expln/metamath-lamp#65]
As mentioned here https://github.com/expln/metamath-lamp/pull/50#issuecomment-1567234813 there are pros and cons of keeping the guide in a separate repo. But number and significance of pros is greater than cons, so I think it is better to move the guide to a new repo. I am not against "lamp-guide" name.

**Pros**:
> a separate repo would indeed focus each repo

> The big advantage of putting it in the Metamath org is that if someone dies, it's easy to continue. Of course, please don't die soon on us :-).

XD XD XD

> one advantage of a separate repo, in the metamath org, is that it'd get more visibility and maybe more would help improve it. That's a decent argument for doing it.

**Cons**:
> A problem with this approach is that this separation often leads to skew, that is, the documentation and code increasingly diverge because code changes don't naturally lead to documentation.

This should not be a big problem. Each version of metamath-lamp has its unique URL. We can specify in the guide which version it describes. I will try to update the guide as soon as I release a new version. We should keep guides for all the previous versions so it should be easy to select a version of mm-lamp and the corresponding guide to read it without being annoyed by significant discrepancies.

**Comment by david-a-wheeler** [comment]
Per this issue, I've set up the new guide repo here:
https://github.com/metamath/lamp-guide/

Let's wait a day or two to see if there are any serious objections. I can't imagine there would be, but I try to give a little time in case there's a surprise. Then I think the links should start pointing there.

You have read/write permissions on this new lamp-guide repo.

**Comment by expln** [comment]
Thank you!

**Comment by david-a-wheeler** [comment]
Note: This will be completed by merging #66.

**Comment by expln** [comment]
Thanks David!
