### ISSUE TITLE
Automatically start "unify all" after the editor state is loadded

### ISSUE THREAD

**Issue by expln** [expln/metamath-lamp#68]
Add optional automatic "unify all" action right after the mm-lamp page loaded. This will add time for the initial loading. So experienced users may turn this off. But for new users this will allow them to see green checkmarks and visualizations without unifying first. This will be useful for small examples distributed via URL.

This also may be implemented via a parameter in the URL. So the author of the URL decides how the page should open. Probably this second option is better.

**Comment by david-a-wheeler** [comment]
I like this idea!

**Comment by expln** [comment]
This feature is implemented in version [22](https://expln.github.io/lamp/v22/index.html). There is a new setting `Automatically "Unify All"` on the settings tab. It is On by default. When it is On, mm-lamp invokes "unify all" each time the editor content is changed. As a side effect, it closes this issue because this new feature invokes "unify all" after opening an editor by navigating to an mm-lamp URL too.
