### ISSUE TITLE
Compile error with MM_cmp_root in develop branch

### ISSUE THREAD

**Issue by billh0420** [expln/metamath-lamp#71]
If we want to make and push changes, do we work in the main branch or the develop branch?

There is a compile error for MM_cmp_root in develop branch at line 139:

================

       let (tabsSt, tabId) = tabsSt->Expln_React_UseTabs.addTab( 
                         ~label, ~closable=true, ~data=ExplorerFrame({label:label}), ~doOpen=true, ()
            )
================

In VSCode, the error message is:

================

This function has type
    (
  Expln_React_UseTabs.state<'a>,
  ~label: string,
  ~closable: bool,
  ~data: 'a,
) => (Expln_React_UseTabs.state<'a>, Expln_React_UseTabs.tabId)
  It only accepts 4 arguments; here, it's called with more.

================

**Comment by expln** [comment]
Hi @billh0420,

> If we want to make and push changes, do we work in the main branch or the develop branch?

For now please use the develop branch for this purpose. 
I am developing in the develop branch, and merging develop to master right before I want to release a new version. In the future I may come up with another approach if the current one becomes inconvenient.

> There is a compile error for MM_cmp_root in develop branch

There was an issue with @expln/utils dependency. I've just recently fixed it. Please try again. You may want to do the next actions:
1) pull changes to your local develop branch
2) run `npm install`
3) run `npm run clean-and-compile-with-deps`

I am closing this issue. Please feel free to reopen it if I missed something or you have related questions.
