### ISSUE TITLE
Add easy access to guide

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#72]
Now that there's a guide at https://lamp-guide.metamath.org it'd be good if the tool made access to it easy.

A few ideas:
* A button that creates a new tab & shows the contents
* Add a "guide" tab that views lamp-guide.metamath.org (only load it when it's first requested). One advantage of an embedded tab is that if the user has "lots of browser tabs", this would make the guide information clearly paired with the tool.

**Comment by expln** [comment]
I think tabs become overloaded (especially after adding a proof explorer) . I plan to add a question mark button somewhere on the context selector area when it is expanded. It will open a simple popup with some short text explanations and links to the guide and to the mm-lamp repo.

**Comment by expln** [comment]
A button with text `About this application` is added on the Settings tab. When clicked, it opens a modal window with several references including a reference to the guide.

**Comment by david-a-wheeler** [comment]
Awesome! Thank you!
