### ISSUE TITLE
Add "browse" tab to browse existing proofs (low priority)

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#73]
It'd be nice to be able to browse *existing* loaded proofs, using the same proof displays available for the final proof along with its description:

* Proofs in the database can often provide examples/hints showing how to do something
* A description of a proof can provide hints in how to use it that'd be nice to see.
* The proof displayer can show inessential steps, which is really nice, especially when trying to explain how Metamath works.

It'd be nice to have a "browse" tab that lets you select a statement, then show the proof (with and without inessential (syntax) steps). It'd also be nice for the "Search" dialogue to let you select a statement and then press a new button "Browse" that switches to the Browse tab to show the selected statement.

The "Browse" tab might remember which statements it's shown, with "<" and ">" buttons to show "previously browsed" and "next browsed".

Low priority, but you've done the *hard* work to implement this, it'd be awesome to do the rest. This could be especially useful when working disconnected.

**Comment by expln** [comment]
This is almost ready. Please check it here https://expln.github.io/lamp/dev/index.html

The tab is named "Explorer". It has basic filters. The "pattern" filter works the same way as in the search. There is no "apply filter" button, you have to press Enter in one of the text fields of the filter. The list of assertions contains basic info. Clicking on `>` sign to the left of a label opens the description for this assertion. Clicking a label opens this assertion in a new tab.

Currently disjoint variables are not shown. I will add it soon.

Also I am planning to add links to metamath.org proof explorer, but a bit later.

**Comment by david-a-wheeler** [comment]
That is really cool! I like it!

One thing this does *not* do is show the proof steps. It'd be awesome if it could show the proof steps of a theorem (e.g. call the current code to show the steps, with or without non-essential steps).

**Comment by david-a-wheeler** [comment]
So I propose leaving this issue open, since Explorer doesn't show the specific proofs. But explorer looks great, I look forward to the next release!

**Comment by expln** [comment]
> One thing this does not do is show the proof steps.

Not sure what you mean by proof steps. If you click on an assertion label it will open proof steps in a new tab.

![image](https://github.com/expln/metamath-lamp/assets/47696142/6f8cc7e4-dfbf-4001-b082-a04b2bd7f37c)

**Comment by david-a-wheeler** [comment]
Ooooh!! That is *awesome*! Yes, that *does* provide the functions I was hoping for, and even more. The ability to alt-click on ranges of statements (such as hypotheses and conclusions), and the ability to click on a step & expand that to yet another tab, is simply outstanding. WOW!!

 A few notes:

* This awesome capability is hidden, I certainly didn't notice it. Is there a way to make it more obvious that "clicking* on the statement name expands it? At the least, maybe include the *number* and word Theorem/Axiom as part of the clickable range. E.g., "43 Theorem mpdd" would be clickable, not just "mpdd". That would increase the likelihood that a user would notice it.
* Once the user creates many tabs, it scrolls off to the right in an awkward way. Can the tab bar be modified so that if it's "too wide" the excess gets pushed into a "..." list, to prevent the excess scrolling? That would probably be especially awkward on a smartphone, which is a key use case for me.
* I suggest making the dynamic tabs even more clearly distinguished from the fixed ones. Maybe italicize them in the tab bar? Imagine having a theorem called "EDITOR" :-).

In the longer term it'd be awesome if the proof display could support an option flag "Show only essential steps [Yes/no, default Yes]". Being able to show inessential steps would make it easier to explain "how Metamath works".

**Comment by david-a-wheeler** [comment]
Actually, for axioms, it'd be better to show the type proof (and link to it from the explorer). Thar would also be consistent with the metamath web site.

**Comment by expln** [comment]
JFYI
There is a known bug in dev:

load set.mm, find r19.12 in the explorer, open r19.12 to see its proof - error in the console: 
        DOMException: Failed to execute 'querySelectorAll' on 'Document': '#tbl-r19.12 .step' is not a valid selector.

**Comment by david-a-wheeler** [comment]
@expln - thanks for the heads-up! In the lamp-guide I do mention the explorer capabilities in development, but I did my best to make clear it's a *future* capability, not one in the released program. It should be obvious to them if they click on the development version, and if they use a development version they should *expect* that some problems may occur.

**Comment by expln** [comment]
Yes, I saw you mentioned this. Thank you very much!
I mentioned here this bug just for you and everyone who may read it to know it exists and I already know it. So no need to report this bug, if anyone wanted to report :)

**Comment by expln** [comment]
> At the least, maybe include the number and word Theorem/Axiom as part of the clickable range.

That's a good and simple for implementation idea, I will do it.

I will check what I can do with tabs.

>Actually, for axioms, it'd be better to show the type proof (and link to it from the explorer). Thar would also be consistent with the metamath web site.

That should not be difficult to implement. I will do it. Thanks for the idea.

**Comment by expln** [comment]
Almost everything what was discussed is implemented:

* The number and word Theorem/Axiom are included as part of the clickable range.
* It is possible to show a type proof for axioms. It is not shown by default, because it takes some time to generate. But if you click "Show syntax breakdown" button, a type proof will be shown.
* Tabs were made wider, so now it is easier to click them. But the problem with tabs overflowing to the right is not resolved. It requires some "expert" level of UI development skills, which I don't have.

**Comment by david-a-wheeler** [comment]
> It requires some "expert" level of UI development skills, which I don't have.

I've made a lot of comments, & no doubt will sent you many more. but overall I think you're doing marvelously.

**Comment by expln** [comment]
Thank you :)
