### ISSUE TITLE
Should name in package.json be "metamath-lamp"?

### ISSUE THREAD

**Issue by billh0420** [expln/metamath-lamp#74]
The current name in package.json is "learn-js-react-app". Should it be  "metamath-lamp" ?

I suspect that it doesn't make a difference since the name is probably taken from bsconfig.json.

It probably only matters if methamath were a package.

But, no matter, it seems that it would be clearer if both names matched.

**Comment by david-a-wheeler** [comment]
Probably. It should also be in the npm registry that way, or there's a risk someone else will create it to create a typosquatting attack.

**Comment by expln** [comment]
> The current name in package.json is "learn-js-react-app". Should it be "metamath-lamp" ?

You are right. I will fix it soon. Thanks for noticing this.

> It should also be in the npm registry that way, or there's a risk someone else will create it to create a typosquatting attack.

mm-lamp is not published in the npm registry. If I decide to extract some functionality into a separate npm package, then I will publish it as @expl/metamath-lamp   And the expln prefix is already taken by me in the npm registry.
