### ISSUE TITLE
Change icon name "substitution" to "replacement"

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#75]
In Metamath the fundamental operation implemented by the tool is called "substitution". I suggest always using the word "replacement" (e.g., "apply replacement") to, for example, change a work variable to something else.

Consistently using different terms for different ideas will make things easier to understand. I've create a PR switching lamp-guide to always use "replacement" for this case.

The dialogue box already uses "Replace what", so it'd be more consistent even within metamath-lamp.

**Comment by expln** [comment]
From PR https://github.com/expln/metamath-lamp/pull/102

> The word "substitution" is confusing, because it has multiple meanings. Is it the fundamental Metamath operation? The "A with arrow" icon?

Yes, it is that fundamental operation described in the Metamath book. 

That's what I don't understand. If we want everything to be consistent, why not to rename everything to "substitution"?
`Replace what` -> `Substitute what`
`Replace with` -> `Substitute with`

But `Substitute what` and `Substitute with` sound incorrect, as for me. Because we substitute variables, but, as a result, some expressions get replaced with other expressions. The text fields in the dialog allow to specify what expression we want to replace with what another expression. Then mm-lamp finds a substitution which allows to achieve this and applies the substitution. So the overall operation is called a substitution, but the fields allow to provide expressions to replace. This is how I came up with such naming.

What do you think about this?

**Comment by david-a-wheeler** [comment]
I think it would be much better to consistently use the term "Replacement" for this icon. The icon already uses "Replace What" and "Replace with", it should just always say "Replacement".

What this icon does is *different* from the Metamath substitution built-in operation. Sure, they're related, but not the same thing.

**Comment by expln** [comment]
Could you please explain what is the difference?

**Comment by david-a-wheeler** [comment]
Replacement modifies the *text* of a proof.

Substitution verifies that a given step in a proof is permitted, for a proposed step.

**Comment by david-a-wheeler** [comment]
Put another way: Replacement is an operation on all the statements in the entire given proof (a sequence of statements that are in turn a sequence of symbols).

The substitution process verifies that a specific step is correctly justified. A substitution isn't global across the whole proof, a substitution justifies one step.

**Comment by expln** [comment]
That's interesting. That not how I imagined it. I need some time to re-read according parts of the Metamath book. I will just mention here what I cannot understand. You are writing that `A substitution isn't global across the whole proof, a substitution justifies one step`. But in the book, in C.2.3 Substitution, it is said `the function from EX to EX`, `We also denote (with abuse of notation) by (E) a substitution on a collection of expressions E  EX` - all of that made me feel like a substitution is a global function applicable to many expressions, not to just one step. By this I am just pointing out to what I cannot understand. But I need to re-read this part of the book to refresh my knowledge (I read it last time almost a year ago).

**Comment by david-a-wheeler** [comment]
Yes, it's a substitution on a "collection of expressions". But only does the substitutions on specific expressions, not global across *all* steps of the proof.

In any case, I think merging #102 resolves it.

**Comment by expln** [comment]
I've re-read the "C.2 The Formal Description" section of the Metamath book,
and it only confirmed my view that the substitution in mm-lamp is exactly same as described in the book.

In the book, in the "C.2.3 Substitution" section, a substitution is defined as a function from EX to EX (EX is the set of all expressions).
It is also mentioned in the book that we may apply it not only to individual expressions but to a collection of expressions (with abuse of notation).
But this definition doesn't restrict what that collection of expressions should be.
We may apply this function to any input subset of EX and get output subset of EX.
That's exactly what mm-lamp does. It uses all the statements in the editor as the input for a substitution.

The only place where I noticed a substitution is coupled with something similar to a proof step is in the "C.2.5 Formal Systems" section.
But it is actually a definition of the closure of a pre-statement. It cannot change the definition of a substitution.

Please correct me if I am wrong.

So I think the tooltip in mm-lamp "Apply a substitution to all steps" is correct.

**Comment by david-a-wheeler** [comment]
It's not a question of correctness, it's a question of clarity. I still think it'd be better to use a different word for this specific circumstance. But this is not a hill to die on, if you really want to use the word "substitution" instead, I'll change the documentation to match.

**Comment by expln** [comment]
Yeah, let's use the word "substitution" for that button. At least for now.
