### ISSUE TITLE
Replacement fields should use selections consistently

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#82]
If I understand things correctly, for fragments, the "first one listed" get the first field when you select replacement, but for statements, "the first one selected" is first.

That's an odd inconsistency, and inconsistencies weaken UIs. The rule should be the same in both cases.

I prefer "first one selected". You select what you want to change first, then what you want to change it to, no matter what.

**Comment by expln** [comment]
This is ready on dev.

**Comment by expln** [comment]
This is available in [version 16](https://expln.github.io/lamp/v16/index.html)
