### ISSUE TITLE
Change "statement" to "step" in the UI

### ISSUE THREAD

**Issue by expln** [expln/metamath-lamp#89]
Change "statement" to "step" in the UI where applicable. See https://github.com/metamath/lamp-guide/issues/62#issuecomment-1585619398

**Comment by david-a-wheeler** [comment]
Hopefully implemented in #88

**Comment by david-a-wheeler** [comment]
I think you can close this issue, renaming those places is "ready-on-dev".

**Comment by expln** [comment]
I will close this and other "ready-on-dev" issues when they are in the "latest" version. I hope this will be soon.

**Comment by david-a-wheeler** [comment]
I think you can close this and all other ready-on-dev issues. Congrats!!

**Comment by expln** [comment]
Thank you! 
I was about to ask you to confirm that everything marked as ready-on-dev may be closed. I will close those issues soon.
