### ISSUE TITLE
Please set GitHub description

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#9]
Please set the GitHub description so that others will know what this program is. Other systems use the "description" field to find programs, explain them, etc.

I suggest this description (edit to taste!):

> Metamath-lamp (Lite Assistant for Metamath Proofs) is a GUI-based proof assistant for creating formal mathematical proofs in Metamath that does not require installation (just run it directly using your web browser).

When viewing the main front page <https://github.com/expln/metamath-lamp> look near the top right for a "gear". Click it and it will let you edit the description field (it's currently empty). Thanks!

**Comment by expln** [comment]
This is done!
